name: CI setup for Go

on:
  push:
    branches: [main]
    
jobs: 
  my-job: 
    name: My Job
    runs-on: ubuntu-16.04
    steps: 
    - name: Print a greeting
      run: |
        ls
        echo Hello there!
        
        
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with: 
        go-version: 1.13.7
        
    - name: Check Go Version
      run: | 
        go version
        ls
        
        
    - name: Checkout my codes
      uses: actions/checkout@v2

    - name: Check file system
      run: ls
